<?php 
$fruits = ["apple", "banana", "cherry"]; 
$vegetables = ["carrot", "lettuce", "tomato"]; 
array_push($fruits, "orange", "grape"); 
echo "Setelah array_push():<br>"; 
print_r($fruits); 
echo "<br><br>"; 
$combined = array_merge($fruits, $vegetables); 
echo "Setelah array_merge():<br>"; 
print_r($combined); 
echo "<br><br>"; 
$values = array_values($combined); 
echo "Setelah array_values():<br>"; 
print_r($values); 
echo "<br><br>"; 
$searchFruit = "banana"; 
$index = array_search($searchFruit, $fruits); 
echo "Index dari '$searchFruit' adalah: $index<br><br>"; 
$numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]; 
$evenNumbers = array_filter($numbers, function($number) { 
return $number % 2 == 0;  
}); 
echo "Angka genap:<br>"; 
print_r($evenNumbers); 
echo "<br><br>"; 
sort($fruits); 
echo "Setelah sort() pada fruits:<br>"; 
print_r($fruits); 
echo "<br>"; 
rsort($vegetables);  
echo "Setelah rsort() pada vegetables:<br>"; 
print_r($vegetables); 
echo "<br>"; 
asort($combined);  
echo "Setelah asort() pada combined:<br>"; 
print_r($combined); 
echo "<br>"; 
ksort($combined);  
echo "Setelah ksort() pada combined:<br>"; 
print_r($combined); 
echo "<br>";
